In [38]:
import csv
import os
import pygrib
import numpy as np

In [43]:
# path = '/media/liuyulin101/YulinLiu/WindData'
path = os.getcwd()
datasrc = path + '/DATA/filtered_weather_data/namanl/'
AllFileName = os.listdir(datasrc)

In [81]:
def ReadGRB(fname):
    grbs = pygrib.open(fname)
    wind = grbs.select(shortName = ['u','v'], typeOfLevel='isobaricInhPa', level = lambda l: l>150 and l <=1000)
#     uin = grbs.select(shortName='u', typeOfLevel='isobaricInhPa')
#     vin = grbs.select(shortName='v', typeOfLevel='isobaricInhPa')
    grbs.close()
    return wind

In [75]:
def grb_to_grid(grb_obj):
    """Takes a single grb object containing multiple
    levels. Assumes same time, pressure levels. Compiles to a cube"""
    n_levels = len(grb_obj)
    levels = np.array([grb_element['level'] for grb_element in grb_obj])
    indexes = np.argsort(levels)[::-1] # highest pressure first
    cube = np.zeros([n_levels, grb_obj[0].values.shape[0], grb_obj[1].values.shape[1]])
    for i in range(n_levels):
        cube[i,:,:] = grb_obj[indexes[i]].values
    cube_dict = {'data' : cube, 'units' : grb_obj[0]['units'],
                 'levels' : levels[indexes]}
    return cube_dict

In [96]:
myfile = pygrib.open(datasrc + AllFileName[10])
wind = myfile.select(shortName = 'u', typeOfLevel='isobaricInhPa', level = lambda l: l>150 and l <=1000)
myfile.close()

In [109]:
lats, lons = wind[0].latlons()

In [111]:
lats

array([[ 12.19      ,  12.21992526,  12.2497741 , ...,  14.38059809,
         14.3571172 ,  14.33355369],
       [ 12.29279317,  12.32275323,  12.35263677, ...,  14.48590525,
         14.46239779,  14.43880759],
       [ 12.39561914,  12.42561397,  12.45553218, ...,  14.59124271,
         14.56770869,  14.54409185],
       ..., 
       [ 54.41570415,  54.45454146,  54.49326792, ...,  57.22745468,
         57.19765424,  57.16774151],
       [ 54.50134592,  54.54018635,  54.57891591, ...,  57.31322725,
         57.28342647,  57.25351336],
       [ 54.58688227,  54.62572575,  54.6644583 , ...,  57.39888823,
         57.36908718,  57.33917377]])

In [107]:
wind[0].values

array([[ 23.10819435,  22.98319435,  22.98319435, ...,  19.98319435,
         20.10819435,  20.10819435],
       [ 23.10819435,  22.98319435,  22.98319435, ...,  19.98319435,
         19.98319435,  20.10819435],
       [ 23.23319435,  23.10819435,  22.98319435, ...,  19.85819435,
         19.85819435,  19.98319435],
       ..., 
       [  8.73319435,   8.60819435,   8.60819435, ...,   1.23319435,
          1.23319435,   1.23319435],
       [  8.60819435,   8.60819435,   8.60819435, ...,   0.98319435,
          0.98319435,   0.98319435],
       [  8.60819435,   8.60819435,   8.60819435, ...,   0.85819435,
          0.85819435,   0.85819435]])

In [103]:
wind[0].data()

(array([[ 23.10819435,  22.98319435,  22.98319435, ...,  19.98319435,
          20.10819435,  20.10819435],
        [ 23.10819435,  22.98319435,  22.98319435, ...,  19.98319435,
          19.98319435,  20.10819435],
        [ 23.23319435,  23.10819435,  22.98319435, ...,  19.85819435,
          19.85819435,  19.98319435],
        ..., 
        [  8.73319435,   8.60819435,   8.60819435, ...,   1.23319435,
           1.23319435,   1.23319435],
        [  8.60819435,   8.60819435,   8.60819435, ...,   0.98319435,
           0.98319435,   0.98319435],
        [  8.60819435,   8.60819435,   8.60819435, ...,   0.85819435,
           0.85819435,   0.85819435]]),
 array([[ 12.19      ,  12.21992526,  12.2497741 , ...,  14.38059809,
          14.3571172 ,  14.33355369],
        [ 12.29279317,  12.32275323,  12.35263677, ...,  14.48590525,
          14.46239779,  14.43880759],
        [ 12.39561914,  12.42561397,  12.45553218, ...,  14.59124271,
          14.56770869,  14.54409185],
        ...,

In [71]:
%timeit ReadGRB(datasrc + AllFileName[10])

1 loop, best of 3: 148 ms per loop


In [9]:
uin, vin = ReadGRB(datasrc + AllFileName[10])
a = uin[0]
b = uin[1]
c = vin[10]

In [37]:
a.latlons()[1]

array([[-133.459     , -133.35382879, -133.24861012, ...,  -65.30358218,
         -65.19490391,  -65.08626455],
       [-133.4896784 , -133.38443247, -133.27913898, ...,  -65.27936503,
         -65.17060391,  -65.06188181],
       [-133.52040446, -133.41508372, -133.3097153 , ...,  -65.25510899,
         -65.14626491,  -65.03745993],
       ..., 
       [-152.76156362, -152.61422451, -152.46674032, ...,  -49.77230343,
         -49.61380974,  -49.45544487],
       [-152.82847374, -152.68100732, -152.53339539, ...,  -49.71728991,
         -49.55863314,  -49.40010561],
       [-152.8955295 , -152.74793564, -152.60019583, ...,  -49.66214743,
         -49.5033273 ,  -49.34463683]])